[bits 64]

%macro __pushall 0

    push rax
    push rbx
    push rcx
    push rdx
    push rsi
    push rdi
    push rbp
    push r8
    push r9
    push r10
    push r11
    push r12
    push r13
    push r14
    push r15

%endmacro

%macro __popall 0

    pop r15
    pop r14
    pop r13
    pop r12
    pop r11
    pop r10
    pop r9
    pop r8
    pop rbp
    pop rdi
    pop rsi
    pop rdx
    pop rcx
    pop rbx
    pop rax

%endmacro

__handle_raw:
    cld
    __pushall

    mov rdi, rsp
    call handle_isr
    mov rsp, rax

    __popall
    add rsp, 16 ; pop error code and interrupt number
    
    iretq

__handle_:
    push rax
    push rcx
    push rdx
    push rbx
    push rsp
    push rbp
    push rsi
    push rdi
    push r8
    push r9
    push r10
    push r11
    push r12
    push r13
    push r14
    push r15

    xor rax, rax
    mov ax, ds
    push rax
    mov ax, 0x0
    mov ds, ax
    mov es, ax

    cld
    mov rdi, rsp

    extern handle_isr
    call handle_isr

    pop rax
    mov ds, ax
    mov es, ax

    mov rsp, rax
    
    pop r15
    pop r14
    pop r13
    pop r12
    pop r11
    pop r10
    pop r9
    pop r8
    pop rdi
    pop rsi
    pop rbp
    pop rbx
    pop rdx
    pop rcx
    pop rax

    add rsp, 16
    jmp $
    iretq


%macro INTERRUPT_NAME 1
dq __interrupt%1
%endmacro
%macro INTERRUPT_ERR 1
__interrupt%1:
  cli
  push  %1
  jmp __handle_raw
%endmacro
%macro   INTERRUPT_NOERR 1
__interrupt%1:
  cli
  push  0
  push  %1
  jmp __handle_raw
%endmacro

INTERRUPT_NOERR 0
INTERRUPT_NOERR 1
INTERRUPT_NOERR 2
INTERRUPT_NOERR 3
INTERRUPT_NOERR 4
INTERRUPT_NOERR 5
INTERRUPT_NOERR 6
INTERRUPT_NOERR 7
INTERRUPT_ERR   8
INTERRUPT_NOERR 9
INTERRUPT_ERR   10
INTERRUPT_ERR   11
INTERRUPT_ERR   12
INTERRUPT_ERR   13
INTERRUPT_ERR   14
INTERRUPT_NOERR 15
INTERRUPT_NOERR 16
INTERRUPT_ERR 17
INTERRUPT_NOERR 18
INTERRUPT_NOERR 19
INTERRUPT_NOERR 20
INTERRUPT_NOERR 21
INTERRUPT_NOERR 22
INTERRUPT_NOERR 23
INTERRUPT_NOERR 24
INTERRUPT_NOERR 25
INTERRUPT_NOERR 26
INTERRUPT_NOERR 27
INTERRUPT_NOERR 28
INTERRUPT_NOERR 29
INTERRUPT_ERR   30
INTERRUPT_NOERR 31

INTERRUPT_NOERR 32
INTERRUPT_NOERR 33
INTERRUPT_NOERR 34
INTERRUPT_NOERR 35
INTERRUPT_NOERR 36
INTERRUPT_NOERR 37
INTERRUPT_NOERR 38
INTERRUPT_NOERR 39
INTERRUPT_NOERR 40
INTERRUPT_NOERR 41
INTERRUPT_NOERR 42
INTERRUPT_NOERR 43
INTERRUPT_NOERR 44
INTERRUPT_NOERR 45
INTERRUPT_NOERR 46
INTERRUPT_NOERR 47
INTERRUPT_NOERR 48
INTERRUPT_NOERR 49
INTERRUPT_NOERR 50
INTERRUPT_NOERR 51
INTERRUPT_NOERR 52
INTERRUPT_NOERR 53
INTERRUPT_NOERR 54
INTERRUPT_NOERR 55
INTERRUPT_NOERR 56
INTERRUPT_NOERR 57
INTERRUPT_NOERR 58
INTERRUPT_NOERR 59
INTERRUPT_NOERR 60
INTERRUPT_NOERR 61
INTERRUPT_NOERR 62
INTERRUPT_NOERR 63
INTERRUPT_NOERR 64
INTERRUPT_NOERR 65
INTERRUPT_NOERR 66
INTERRUPT_NOERR 67
INTERRUPT_NOERR 68
INTERRUPT_NOERR 69
INTERRUPT_NOERR 70
INTERRUPT_NOERR 71
INTERRUPT_NOERR 72
INTERRUPT_NOERR 73
INTERRUPT_NOERR 74
INTERRUPT_NOERR 75
INTERRUPT_NOERR 76
INTERRUPT_NOERR 77
INTERRUPT_NOERR 78
INTERRUPT_NOERR 79
INTERRUPT_NOERR 80
INTERRUPT_NOERR 81
INTERRUPT_NOERR 82
INTERRUPT_NOERR 83
INTERRUPT_NOERR 84
INTERRUPT_NOERR 85
INTERRUPT_NOERR 86
INTERRUPT_NOERR 87
INTERRUPT_NOERR 88
INTERRUPT_NOERR 89
INTERRUPT_NOERR 90
INTERRUPT_NOERR 91
INTERRUPT_NOERR 92
INTERRUPT_NOERR 93
INTERRUPT_NOERR 94
INTERRUPT_NOERR 95

global __spurious
__spurious:
  iretq

section .data

global __interrupt_vector

__interrupt_vector:
  INTERRUPT_NAME 0
  INTERRUPT_NAME 1
  INTERRUPT_NAME 2
  INTERRUPT_NAME 3
  INTERRUPT_NAME 4
  INTERRUPT_NAME 5
  INTERRUPT_NAME 6
  INTERRUPT_NAME 7
  INTERRUPT_NAME 8
  INTERRUPT_NAME 9
  INTERRUPT_NAME 10
  INTERRUPT_NAME 11
  INTERRUPT_NAME 12
  INTERRUPT_NAME 13
  INTERRUPT_NAME 14
  INTERRUPT_NAME 15
  INTERRUPT_NAME 16
  INTERRUPT_NAME 17
  INTERRUPT_NAME 18
  INTERRUPT_NAME 19
  INTERRUPT_NAME 20
  INTERRUPT_NAME 21
  INTERRUPT_NAME 22
  INTERRUPT_NAME 23
  INTERRUPT_NAME 24
  INTERRUPT_NAME 25
  INTERRUPT_NAME 26
  INTERRUPT_NAME 27
  INTERRUPT_NAME 28
  INTERRUPT_NAME 29
  INTERRUPT_NAME 30
  INTERRUPT_NAME 31

  INTERRUPT_NAME 32
  INTERRUPT_NAME 33
  INTERRUPT_NAME 34
  INTERRUPT_NAME 35
  INTERRUPT_NAME 36
  INTERRUPT_NAME 37
  INTERRUPT_NAME 38
  INTERRUPT_NAME 39
  INTERRUPT_NAME 40
  INTERRUPT_NAME 41
  INTERRUPT_NAME 42
  INTERRUPT_NAME 43
  INTERRUPT_NAME 44
  INTERRUPT_NAME 45
  INTERRUPT_NAME 46
  INTERRUPT_NAME 47
  INTERRUPT_NAME 48
  INTERRUPT_NAME 49
  INTERRUPT_NAME 50
  INTERRUPT_NAME 51
  INTERRUPT_NAME 52
  INTERRUPT_NAME 53
  INTERRUPT_NAME 54
  INTERRUPT_NAME 55
  INTERRUPT_NAME 56
  INTERRUPT_NAME 57
  INTERRUPT_NAME 58
  INTERRUPT_NAME 59
  INTERRUPT_NAME 60
  INTERRUPT_NAME 61
  INTERRUPT_NAME 62
  INTERRUPT_NAME 63
  INTERRUPT_NAME 64
  INTERRUPT_NAME 65
  INTERRUPT_NAME 66
  INTERRUPT_NAME 67
  INTERRUPT_NAME 68
  INTERRUPT_NAME 69
  INTERRUPT_NAME 70
  INTERRUPT_NAME 71
  INTERRUPT_NAME 72
  INTERRUPT_NAME 73
  INTERRUPT_NAME 74
  INTERRUPT_NAME 75
  INTERRUPT_NAME 76
  INTERRUPT_NAME 77
  INTERRUPT_NAME 78
  INTERRUPT_NAME 79
  INTERRUPT_NAME 80
  INTERRUPT_NAME 81
  INTERRUPT_NAME 82
  INTERRUPT_NAME 83
  INTERRUPT_NAME 84
  INTERRUPT_NAME 85
  INTERRUPT_NAME 86
  INTERRUPT_NAME 87
  INTERRUPT_NAME 88
  INTERRUPT_NAME 89
  INTERRUPT_NAME 90
  INTERRUPT_NAME 91
  INTERRUPT_NAME 92
  INTERRUPT_NAME 93
  INTERRUPT_NAME 94
  INTERRUPT_NAME 95
 
