name: Meson

on:
  push:
    branches: [ master, new-kernel ]
  pull_request:
    branches: [ master ]

env:
  # Customize the Meson build type here  
  BUILD_TYPE: release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Configure
      run: pip3 install meson ninja && sudo apt install gcc-aarch64-linux-gnu qemu-system-arm && meson setup -Dbuildtype=${{env.BUILD_TYPE}} --cross-file assets/mrk-aarch64.txt build

    - name: Build
      # Build your program with the given configuration
      run: ninja -C build
    
    - name: Insturmentation
      # Run kernel in qemu and save output to logfile
      run: qemu-system-aarch64 -no-reboot -M virt -d int -cpu cortex-a72 -drive if=pflash,format=raw,file=./assets/sabaton_virt_aa64.bin,readonly=on -m 2G -serial stdio -smp 2 -device ramfb -fw_cfg opt/Sabaton/kernel,file=build/kernel/mrk-aa64.elf 2>&1 | tee Loggin.txt
      
    - name: Distribute Kernel
      uses: actions/upload-artifact@v2.2.4
      with:
        # Artifact name
        name: Beta Kernel Binary
        # A file, directory or wildcard pattern that describes what to upload
        path: build/kernel/mrk-aa64.elf
        
    - name: Distribute Log
      uses: actions/upload-artifact@v2.2.4
      with:
        # Artifact name
        name: Beta Kernel Log (QEMU)
        # A file, directory or wildcard pattern that describes what to upload
        path: Loggin.txt
