name: Meson

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  # Customize the Meson build type here  
  BUILD_TYPE: release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Configure
      run: pip3 install meson ninja && sudo apt install nasm clang-12 && cd kernel && CXX=clang++ CC=clang CXX_LD=lld meson setup -Dbuildtype=${{env.BUILD_TYPE}} build

    - name: Build
      # Build your program with the given configuration
      run: cd kernel && ninja -C build && git submodule init && git submodule update

    - name: Bundle
      run: strip build/mrk.elf && ../tools/bundle_iso.sh build ..
      
    - name: Distribute
      uses: actions/upload-artifact@v2.2.4
      with:
        # Artifact name
        name: Beta ISO
        # A file, directory or wildcard pattern that describes what to upload
        path: kernel/build/mrk-image.iso 
