name: Meson

on:
  push:
    branches: [ master, new-kernel ]
  pull_request:
    branches: [ master ]

env:
  # Customize the Meson build type here  
  BUILD_TYPE: release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Configure
      run: pip3 install meson ninja && sudo apt install gcc-aarch64-linux-gnu && meson setup -Dbuildtype=${{env.BUILD_TYPE}} --cross-file assets/mrk-aarch64.txt build

    - name: Build
      # Build your program with the given configuration
      run: ninja -C build
    
    - name: Distribute Kernel
      uses: actions/upload-artifact@v2.2.4
      with:
        # Artifact name
        name: Beta Kernel Binary
        # A file, directory or wildcard pattern that describes what to upload
        path: build/kernel/mrk-aa64.elf
